language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 2.7.10
install:
  - pip install unittest2
  - pip install adafruit_pca9685
  - pip install flask
  - pip install flask_bootstrap
  - pip install flask_sqlalchemy
script: python smarslab_test_suite.py
